server.port=${PORT:8080}
spring.profiles.default=dev

spring.h2.console.enabled=false
spring.h2.console.path=/h2-console

app.seed-default-users=false
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
